### ISSUE TITLE
Variables parameter doesn't work

### ISSUE THREAD

**Issue by pawel-starczewski** [bugbug-io/bugbug-github-action#4]
Hey,

I am trying to pass temporary variable for a duration of a single run, but it is not being picked up by the runner:

.yml
`- name: Run BugBug Cloud Runner
        id: run-bugbug-tests
        uses: bugbug-io/bugbug-github-action@v1.2.0
        with:
          apiToken: ${{ secrets.BUGBUG_API_TOKEN }}
          suiteId: "my-id"
          profileName: Default
          variables: "jira_key=some_name"
          debug: "true"
`

console output:
`
Run /home/runner/work/_actions/bugbug-io/bugbug-github-action/v1.2.0/.github/scripts/run.sh
true Default jira_key=some_name
----- DEBUG -----
{
  url: 'https://app.bugbug.io/api/v1/suiteruns/',
  headers: Object [AxiosHeaders] {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    Authorization: 'Token ***',
    'User-Agent': 'BugBug CLI 8.14.2'
  },
  params: {},
  data: {
    suite_id: 'my-id',
    profile_name: 'Default',
    variables: [],
    triggeredBy: 'github'
  }
}
`

How can I workaround this issue?

**Comment by pbylina** [comment]
Indeed it looks like a bug. A potential fix will arrive tomorrow. Thanks for reporting!

**Comment by simplypixi** [comment]
@pawel-starczewski 
I'm happy to say, we released new version (1.2.1) which covers this issue. :)

**Comment by pawel-starczewski** [comment]
Works, thanks!
